---
# local frame must be given in utm coordinates
local_frame:
    east:     &local_frame_east   360284.0
    north:    &local_frame_north 4813595.0
    alt:      &local_frame_alt         0.0
    utm_zone: &local_frame_utm_zone    31N

# flight area in local coordinates
flight_area: &flight_area [[-10000.0, -10000.0, 185.0], [10000.0, 10000.0, 4000.0]]
allow_warm_start: True
# allow_warm_start: False

# database config
database:
    enable_save: False
    filepath: '/home/fseguin/work/nephelae_data/default.neph'
    overwrite_existing: True

# mesonh_files:  &mesonh_files '/home/pnarvor/work/nephelae/data/nephelae-remote/MesoNH02/bomex_hf.nc'
# mesonh_files:  &mesonh_files '/media/pnarvor/nephelae-data/MesoNH/bomex_hf.nc'
mesonh_files:  &mesonh_files '/home/pnarvor/work/nephelae/data/MesoNH-2019-02/REFHR.1.ARMCu.4D.nc'
# Setting this to true will activate feedback to WORLD_ENV requests
wind_feedback: False

wind_map:
    type: 'WindObserverMap'
    name: 'Horizontal Wind'
    sampleName: ['UT', 'VT']

# mesonh_origin: &mesonh_origin [0.0, 0.0, 0.0, 0.0]
mesonh_origin: &mesonh_origin [200.0, 8000.0, -1000.0, 100.0]
# mesonh_origin: &mesonh_origin [0.0, -731.7, -2126.5, 0.0]

# Default fields. Used to define yaml aliases, to define values in one single place.
defaults:
    start: &start_defaults
        - Length: [3]
        - SimpleBounds: [*flight_area]
    circle_radius:
        - &circle_radius_min  80.0
        - &circle_radius_max 500.0
        - defaults: &circle_radius_defaults
            - DefaultValue: [80.0]
            - SimpleBounds: [[*circle_radius_min, *circle_radius_max]]
    altitude:
        - &altitude_min  185.0
        - &altitude_max 4000.0
        - defaults: &altitude_defaults
            - SimpleBounds: [[*altitude_min, *altitude_max]]
    drift:
        - &xdrift_min -10.0
        - &xdrift_max  10.0
        - &ydrift_min -10.0
        - &ydrift_max  10.0
        - &zdrift_min  -3.0
        - &zdrift_max   3.0
        - drift: &drift_defaults
            - DefaultValue: [[0.0,0.0,0.0]]
            - Length: [3]
            - SimpleBounds: [[[*xdrift_min, *ydrift_min, *zdrift_min],
                              [*xdrift_max, *ydrift_max, *zdrift_max]]]
        - hdrift: &hdrift_defaults
            - Length: [2]
            - SimpleBounds: [[[*xdrift_min, *ydrift_min],
                              [*xdrift_max, *ydrift_max]]]
        - zdrift: &zdrift_defaults
            - SimpleBounds: [[*zdrift_min, *zdrift_max]]

    lace: &lace_defaults
        parameters:
            start: *start_defaults
            first_turn_direction:
                - DefaultValue:  [1.0]
                - AllowedValues: [[-1.0, 1.0]]
            circle_radius: *circle_radius_defaults
            drift: *drift_defaults
        updatables:
            hdrift: *hdrift_defaults
            zdrift: *zdrift_defaults

    rosette: &rosette_defaults
        parameters:
            start: *start_defaults
            first_turn_direction:
                - DefaultValue:  [1.0]
                - AllowedValues: [[-1.0, 1.0]]
            circle_radius: *circle_radius_defaults
            drift: *drift_defaults
        updatables:
            hdrift: *hdrift_defaults
            zdrift: *zdrift_defaults

    spiral3d: &spiral3d_defaults
        parameters:
            start: *start_defaults
            alt_stop: *altitude_defaults
            radius_start: *circle_radius_defaults
            radius_stop:  *circle_radius_defaults
            drift: *drift_defaults
        updatables:
            hdrift: *hdrift_defaults
            zdrift: *zdrift_defaults

aircrafts:
    # 9:
    #     plugins:
    #         - MesonhProbe:
    #             mesonhFiles: *mesonh_files
    #             mesonhVariables: ['RCT', 'WT', 'THT', ['UT','VT']]
    #             rctFeedback: True
    #             mesonhOrigin: *mesonh_origin
    #         - Missions:
    #             backup_file: 'backup_200.bin'
    #             Lace: *lace_defaults
    #             Rosette: *rosette_defaults
    #             Spiral3D: *spiral3d_defaults
    #         - CloudCenterTracker:
    #             mapWhereCenterIs: 'LWC'
    #         - MissionWindUpdater:
    #             period: 10.0
    200:
        plugins:
            - MesonhProbe:
                mesonhFiles: *mesonh_files
                mesonhVariables: ['RCT', 'WT', 'THT', ['UT','VT']]
                rctFeedback: True
                mesonhOrigin: *mesonh_origin
            - Missions:
                backup_file: 'backup_200.bin'
                Lace: *lace_defaults
                Rosette: *rosette_defaults
                Spiral3D: *spiral3d_defaults
            - CloudCenterTracker:
                mapWhereCenterIs: 'LWC'
            - MissionWindUpdater:
                period: 10.0
            - CloudSensor
            - MeteoStick
    # 201:
    #     plugins:
    #         - MesonhProbe:
    #             mesonhFiles: *mesonh_files
    #             mesonhVariables: ['RCT', 'WT', 'THT', ['UT','VT']]
    #             rctFeedback: True
    #             mesonhOrigin: *mesonh_origin
    #         - Missions:
    #             backup_file: 'backup_201.bin'
    #             Lace: *lace_defaults
    #             Rosette: *rosette_defaults
    #             Spiral3D: *spiral3d_defaults
    #         # - MissionWindUpdater:
    #         #     period: 10.0
    # 202:
    #     plugins:
    #         - MesonhProbe:
    #             mesonhFiles: *mesonh_files
    #             mesonhVariables: ['RCT', 'WT', 'THT', ['UT','VT']]
    #             rctFeedback: False
    #             mesonhOrigin: *mesonh_origin
    # 203:
    #     plugins:
    #         - MesonhProbe:
    #             mesonhFiles: *mesonh_files
    #             mesonhVariables: ['RCT', 'WT', 'THT', ['UT','VT']]
    #             rctFeedback: False
    #             mesonhOrigin: *mesonh_origin
    # 204:
    #     plugins:
    #         - MesonhProbe:
    #             mesonhFiles: *mesonh_files
    #             mesonhVariables: ['RCT', 'WT', 'THT', ['UT','VT']]
    #             rctFeedback: False
    #             mesonhOrigin: *mesonh_origin

maps:
    kernels:
        lwc_kernel:
            type: 'WindKernel'
            length_scales: [120.0, 60.0, 60.0, 60.0]
            # length_scales: [3000.0, 60.0, 60.0, 60.0]
            variance: 1.0e-8
            noise_variance: 1.0e-10
    LWC:
        name: 'Liquid Water'
        type: 'GprMap'
        kernel: 'lwc_kernel'
        database_tags: ['RCT']
        data_range: [0.0, 1.0e-4]
        threshold: 2.0e-4
        std_map: 'Liquid Water std' # optional
        border_map: 'Liquid Water border' # optional

    clouds:
        name: 'Liquid Water (MesoNH)'
        type: 'MesonhMap'
        mesonh_variable: 'RCT'
        origin: *mesonh_origin
    # thermals:
    #     name: 'Vertical Wind (MesoNH)'
    #     type: 'MesonhMap'
    #     mesonh_variable: 'WT'
    #     origin: *mesonh_origin
